repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 73413df07b4ab0bf103ca1ae73c7cec5c0ace593
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: bbc3dc1f890007061f18f17e2334f216ea9e5df7
  hooks:
    - id: mypy
      additional_dependencies:
        - click>=8.5.0
        - eth-typing>=6.0.0
        - eth-utils>=6.0.0
        - pycryptodome>=3.23.0
        - py-ecc>=8.0.0
        - ssz>=0.6.0
      files: ^ethstaker_deposit/
      args: [--config-file, mypy.ini]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b
  hooks:
    - id: check-json
      files: ^ethstaker_deposit/intl
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: detect-private-key
    - id: check-ast
    - id: debug-statements
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: mixed-line-ending
    - id: check-case-conflict
    - id: requirements-txt-fixer
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: 745eface02aef23e168a8afb6b5737818efbea95
  hooks:
    - id: shellcheck
